name: Create Table
on:
  push:
    branches:
      - test_table_script
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: oecrkeanazdxowjcpjqr

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Check if table alr exists
        run: |
          result=$(supabase table list --project-ref $PROJECT_ID | grep "Reform Map")
          if [ -n "$result" ]; then
            echo "Table exists, dropping it"
            supabase table drop "Reform Map" --project-ref $PROJECT_ID
          else
            echo "Table doesn't exist"
          fi

