name: Create Simple Table
on:
  push:
    branches:
      - test_table_script


jobs:
  create-table:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: oecrkeanazdxowjcpjqr

    steps:   
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Debug
        run: |
          ls -l /node-modules/supabase
    
      - name: Install Supabase CLI
        run: npm i supabase --save-dev

      - name: Add Supabase CLI to PATH
        run: export PATH=$PATH:/node-modules/supabase

      - name: Create table
        run: |
          supabase create table table_test --schema public --columns "firstcolumn:text,secondcolumn:bigint"

      - name: Check
        run: echo "table created!"