name: Create Simple Table
on:
  push:
    branches:
      - test_table_script


jobs:
  Create-Table:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: oecrkeanazdxowjcpjqr

    steps:   
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create table
        run: |
          supabase create table table_test --schema public --columns "firstcolumn:text,secondcolumn:bigint"

      - name: Check
        run: echo "table created"