name: Create Simple Table
on:
  push:
    branches:
      - test_table_script

jobs:
  create-table:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: oecrkeanazdxowjcpjqr

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

          # - run: supabase functions deploy --project-ref $PROJECT_ID

      - name: Init
        run: supabase init 

      - name: Configure Supabase
        run: supabase link --project-ref $PROJECT_ID 

      - name: Create table
        run: |
          supabase create table table_test --schema public --columns "firstcolumn:text,secondcolumn:bigint"

      - name: Check
        run: echo "Table created!"
