name: Deploy to prod
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy-prod:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - name: Archive city_detail/ contents
        run: |
          cd city_detail
          tar -czf ../city_details.tar.gz **/*
      - name: Copy city_detail/ to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRN_SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRN_SERVER_PRIVATE_KEY }}
          source: city_details.tar.gz
          target: /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/city_detail
      - name: Extract on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRN_SERVER_HOST }}
          username: ${{ secrets.PRN_SERVER_USERNAME }}
          key: ${{ secrets.PRN_SERVER_PRIVATE_KEY }}
          script: |
            tar -xzf /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/city_detail/city_details.tar.gz -C /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/city_detail
            rm /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/city_detail/city_details.tar.gz
