name: Sync latitude & longitude
on:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 12 midnight PT
  workflow_dispatch:
jobs:
  update:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run sync-lat-lng
        run: npm run sync-lat-lng
      - name: Check for changes
        id: git_status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Create Pull Request
        if: steps.git_status.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update latitude and longitude"
          title: "Update latitude and longitude"
          body: "This PR syncs the data from https://docs.google.com/spreadsheets/d/15L8hwNEi13Bov81EulgC8Xwt9_wCgofwcH49xHoNlKI/edit?usp=sharing."
          branch: "update-lat-lng"
