name: Create Table
on:
  push:
    branches:
      - test_table_script
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: oecrkeanazdxowjcpjqr

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
      - name: check
        run: echo "upload worked"
